title: Robert Vargas # your name (or website title) here
logo: "/images/IMG_4541.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  <u><b>Business Intelligence Analyst</b></u>
  <br>
  Business minded individual with proficiency in skills important for financial modeling, data analysis, and accounting practices. Keen on utilizing software skills and deductive reasoning to raise effectiveness.
  <br><br>
  <a href="https://rpubs.com/Robato_95">View My RPubs Projects</a> 
  <br>
  <a href="https://public.tableau.com/profile/robert.vargas7196#!/">View My Tableau Portfolio</a> 

  
theme: jekyll-theme-minimal
google_analytics: G-0X9GCHKRC9 # your Google Analytics tracking ID here

